export enum EChar {
  Elesis = 'Elesis',
  Lire = 'Lire',
  Arme = 'Arme',
  Lass = 'Lass',
  Ryan = 'Ryan',
  Ronan = 'Ronan',
  Amy = 'Amy',
  Jin = 'Jin',
  Sieghart = 'Sieghart',
  Mari = 'Mari',
  Dio = 'Dio',
  Zero = 'Zero',
  Rey = 'Rey',
  Lupus = 'Lupus',
  Lin = 'Lin',
  Azin = 'Azin',
  Holy = 'Holy',
  Edel = 'Edel',
  Veigas = 'Veigas',
  Decane = 'Decane',
  AI = 'AI',
  Kallia = 'Kallia',
  Uno = 'Uno',
}

export enum EClassChar {
  class_1 = 'class_1',
  class_2 = 'class_2',
  class_3 = 'class_3',
  class_4 = 'class_4',
  class_5 = 'class_5',
}
