export enum EChars {
  'Elesis' = 'Elesis',
  'Lire' = 'Lire',
  'Arme' = 'Arme',
  'Lass' = 'Lass',
  'Ryan' = 'Ryan',
  'Ronan' = 'Ronan',
  'Amy' = 'Amy',
  'Jin' = 'Jin',
  'Sieghart' = 'Sieghart',
  'Mari' = 'Mari',
  'Dio' = 'Dio',
  'Zero' = 'Zero',
  'Rey' = 'Rey',
  'Lupus' = 'Lupus',
  'Lin' = 'Lin',
  'Azin' = 'Azin',
  'Holy' = 'Holy',
  'Edel' = 'Edel',
  'Veigas' = 'Veigas',
  'Decane' = 'Decane',
  'AI' = 'AI',
  'Kallia' = 'Kallia',
  'Uno' = 'Uno',
}

export enum EEquips {
  elmo = 'elmo',
  cota = 'cota',
  calca = 'calca',
  luva = 'luva',
  bota = 'bota',
  capa = 'capa',
  arma1 = 'arma1',
  arma2 = 'arma2',
  diadema = 'diadema',
  mascara = 'mascara',
  asa = 'asa',
  facas = 'facas',
  escudo = 'escudo',
  anel = 'anel',
  colar = 'colar',
  tornozeleira = 'tornozeleira',
  brinco1 = 'brinco1',
  brinco2 = 'brinco2',
}
